[package]
name = "pblib-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "libcpblib.a"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
